# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='DATA2410_Portfolio2',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\x12\x13\x44\x41TA2410_Portfolio2\"\r\n\x0bNoParameter\"\x1b\n\x03Pos\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"d\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x03(\x05\x12\x11\n\tgame_over\x18\x03 \x01(\x08\x12*\n\x08position\x18\x04 \x03(\x0b\x32\x18.DATA2410_Portfolio2.Pos\"6\n\x07Players\x12+\n\x06player\x18\x01 \x03(\x0b\x32\x1b.DATA2410_Portfolio2.Player\"(\n\tHighScore\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\"@\n\x0bLeaderboard\x12\x31\n\thighScore\x18\x01 \x03(\x0b\x32\x1e.DATA2410_Portfolio2.HighScore\"5\n\x06\x46ruits\x12+\n\tpositions\x18\x01 \x03(\x0b\x32\x18.DATA2410_Portfolio2.Pos2\xdb\x03\n\x04\x44\x61ta\x12\x46\n\nsendPlayer\x12\x1b.DATA2410_Portfolio2.Player\x1a\x1b.DATA2410_Portfolio2.Player\x12O\n\rsendHighScore\x12\x1e.DATA2410_Portfolio2.HighScore\x1a\x1e.DATA2410_Portfolio2.HighScore\x12\x46\n\nsendFruits\x12\x1b.DATA2410_Portfolio2.Fruits\x1a\x1b.DATA2410_Portfolio2.Fruits\x12N\n\ngetPlayers\x12 .DATA2410_Portfolio2.NoParameter\x1a\x1c.DATA2410_Portfolio2.Players0\x01\x12T\n\x0egetLeaderboard\x12 .DATA2410_Portfolio2.NoParameter\x1a .DATA2410_Portfolio2.Leaderboard\x12L\n\tgetFruits\x12 .DATA2410_Portfolio2.NoParameter\x1a\x1b.DATA2410_Portfolio2.Fruits0\x01\x62\x06proto3'
)




_NOPARAMETER = _descriptor.Descriptor(
  name='NoParameter',
  full_name='DATA2410_Portfolio2.NoParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=48,
)


_POS = _descriptor.Descriptor(
  name='Pos',
  full_name='DATA2410_Portfolio2.Pos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='DATA2410_Portfolio2.Pos.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='DATA2410_Portfolio2.Pos.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=77,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='DATA2410_Portfolio2.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DATA2410_Portfolio2.Player.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='DATA2410_Portfolio2.Player.color', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='game_over', full_name='DATA2410_Portfolio2.Player.game_over', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='DATA2410_Portfolio2.Player.position', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=179,
)


_PLAYERS = _descriptor.Descriptor(
  name='Players',
  full_name='DATA2410_Portfolio2.Players',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='DATA2410_Portfolio2.Players.player', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=235,
)


_HIGHSCORE = _descriptor.Descriptor(
  name='HighScore',
  full_name='DATA2410_Portfolio2.HighScore',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='DATA2410_Portfolio2.HighScore.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='DATA2410_Portfolio2.HighScore.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=277,
)


_LEADERBOARD = _descriptor.Descriptor(
  name='Leaderboard',
  full_name='DATA2410_Portfolio2.Leaderboard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='highScore', full_name='DATA2410_Portfolio2.Leaderboard.highScore', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=343,
)


_FRUITS = _descriptor.Descriptor(
  name='Fruits',
  full_name='DATA2410_Portfolio2.Fruits',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='DATA2410_Portfolio2.Fruits.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=345,
  serialized_end=398,
)

_PLAYER.fields_by_name['position'].message_type = _POS
_PLAYERS.fields_by_name['player'].message_type = _PLAYER
_LEADERBOARD.fields_by_name['highScore'].message_type = _HIGHSCORE
_FRUITS.fields_by_name['positions'].message_type = _POS
DESCRIPTOR.message_types_by_name['NoParameter'] = _NOPARAMETER
DESCRIPTOR.message_types_by_name['Pos'] = _POS
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Players'] = _PLAYERS
DESCRIPTOR.message_types_by_name['HighScore'] = _HIGHSCORE
DESCRIPTOR.message_types_by_name['Leaderboard'] = _LEADERBOARD
DESCRIPTOR.message_types_by_name['Fruits'] = _FRUITS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NoParameter = _reflection.GeneratedProtocolMessageType('NoParameter', (_message.Message,), {
  'DESCRIPTOR' : _NOPARAMETER,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.NoParameter)
  })
_sym_db.RegisterMessage(NoParameter)

Pos = _reflection.GeneratedProtocolMessageType('Pos', (_message.Message,), {
  'DESCRIPTOR' : _POS,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.Pos)
  })
_sym_db.RegisterMessage(Pos)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), {
  'DESCRIPTOR' : _PLAYER,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.Player)
  })
_sym_db.RegisterMessage(Player)

Players = _reflection.GeneratedProtocolMessageType('Players', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERS,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.Players)
  })
_sym_db.RegisterMessage(Players)

HighScore = _reflection.GeneratedProtocolMessageType('HighScore', (_message.Message,), {
  'DESCRIPTOR' : _HIGHSCORE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.HighScore)
  })
_sym_db.RegisterMessage(HighScore)

Leaderboard = _reflection.GeneratedProtocolMessageType('Leaderboard', (_message.Message,), {
  'DESCRIPTOR' : _LEADERBOARD,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.Leaderboard)
  })
_sym_db.RegisterMessage(Leaderboard)

Fruits = _reflection.GeneratedProtocolMessageType('Fruits', (_message.Message,), {
  'DESCRIPTOR' : _FRUITS,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:DATA2410_Portfolio2.Fruits)
  })
_sym_db.RegisterMessage(Fruits)



_DATA = _descriptor.ServiceDescriptor(
  name='Data',
  full_name='DATA2410_Portfolio2.Data',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=401,
  serialized_end=876,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendPlayer',
    full_name='DATA2410_Portfolio2.Data.sendPlayer',
    index=0,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_PLAYER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendHighScore',
    full_name='DATA2410_Portfolio2.Data.sendHighScore',
    index=1,
    containing_service=None,
    input_type=_HIGHSCORE,
    output_type=_HIGHSCORE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='sendFruits',
    full_name='DATA2410_Portfolio2.Data.sendFruits',
    index=2,
    containing_service=None,
    input_type=_FRUITS,
    output_type=_FRUITS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getPlayers',
    full_name='DATA2410_Portfolio2.Data.getPlayers',
    index=3,
    containing_service=None,
    input_type=_NOPARAMETER,
    output_type=_PLAYERS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getLeaderboard',
    full_name='DATA2410_Portfolio2.Data.getLeaderboard',
    index=4,
    containing_service=None,
    input_type=_NOPARAMETER,
    output_type=_LEADERBOARD,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getFruits',
    full_name='DATA2410_Portfolio2.Data.getFruits',
    index=5,
    containing_service=None,
    input_type=_NOPARAMETER,
    output_type=_FRUITS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATA)

DESCRIPTOR.services_by_name['Data'] = _DATA

# @@protoc_insertion_point(module_scope)
